### PR TITLE
Draw trivial tokens and indices

### PR DESCRIPTION
**Pull request by emileferreira**
Presently, drawing tokens or indices by themselves (for example, `draw(tokens)` or `draw(indices, "hello")`) results in an empty figure. This adds support for drawing trivial tokens and indices, as feedforward layers.

### CODE REVIEW

**Comment by gailweiss** [comment]
this draws them, but mysteriously labels them with FF in the drawing (instead of X, as they are labeled when drawing computation flows with actual computations). is it possible to get them to show up the same way they would normally?

**Comment by emileferreira** [comment]
They're now labelled 'X' in the computational flow figures. It's not an elegant solution, but the existing code only considers feedforward layers and would need to be rewritten.

**Comment by gailweiss** [comment]
if i understand correctly, you've treated them as their own parents, forcing them into the X row. it seems like a nice solution to me!

Can you add comments to the changes you've made, so it's clear why this special case (len(ffs)==1) exists now? i.e. specifically highlight around all your changes that len(ffs) == 1 implies we are drawing just a tokens/indices sop by itself, and (if it's confusing, eg switching ffs and their parents) explain what (and why) you are doing in this special case

**Comment by emileferreira** [comment]
Thanks. I've added comments to explain the changes.

**Comment by gailweiss** [comment]
it's a nice trick, but i don't like the use of the 'constant' patch as it permanently marks that sequence as a constant, which later creates strange behaviour (e.g. if you do `draw(indices+1);` after having earlier done `draw(indices);`, you will now get a warning that it is drawing a constant. however, the parent-child swap for the base sequence draw was quite nice. i have made a slightly different set of changes, based on your own, which do not cause this issue. i will note them in comments on your code

**Comment by emileferreira** [comment]
I figured that it was safe to (ab)use the `_constant` property of `UnfinishedSequence`, as it's unused besides for that benign warning. I've resolved the warning by resetting the property after drawing, otherwise we can create a new property.

**Comment by emileferreira** [comment]
The trivial case, in which the feedforward layers and their parents are to be swapped, is now identified by the length of the respective lists. This avoids using the `_constant` property and the associated warning.

**Pull request merged**
